apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nginx-dev"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nginx-dev"
      "workload.user.cattle.io/workloadselector": "apps.deployment-develop-nginx-dev"
  template:
    metadata:
      labels:
        "workload.user.cattle.io/workloadselector": "apps.deployment-develop-nginx-dev"
        app: "nginx-dev"
    spec:
      containers:
        - name: "nginx-dev"
          image: "registrypolrare.azurecr.io/nginx-dev"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: "2500m"
              memory: "4096Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
