apiVersion: v1
kind: Service
metadata:
    name: "akspolrare-5fb5"
    labels:
        app: "akspolrare-5fb5"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akspolrare-5fb5"